from __future__ import annotations

from datetime import datetime, timedelta, timezone
from typing import Annotated, Any, Literal

from fastapi import APIRouter, HTTPException, status
from fastapi import Body, Depends
from pydantic import BaseModel, Field
from sqlalchemy import delete, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.core.database import get_db
from app.core.security import get_current_user
from app.models.auth_models import User
from app.models.social_orm import SocialAccount
from app.models.content_orm import ContentItem, PlatformVariant
from app.services.master_publisher import publish_to_all_platforms
from app.services.publishers.assisted_publisher import AssistedPublisher
from app.services.publishers.linkedin_publisher import LinkedInPublisher
from app.services.publishers.twitter_publisher import TwitterPublisher
from app.services.publishers.youtube_publisher import YouTubePublisher
from app.services.media_service import MediaService
from app.services.media_validation import MediaValidationError, probe_url, validate_for_platform
from app.services.token_crypto import try_decrypt_token
from app.workers.publish_task import publish_content_task

# Mounted in app.main at `/api/v1/platforms`
router = APIRouter()


PlatformKey = Literal["youtube", "instagram", "facebook", "x", "twitter", "linkedin"]
AutomationTier = Literal["full_auto", "semi_auto", "assisted"]


def _normalize(platform: str) -> str:
    """Frontend uses 'x', backend stores 'twitter'."""
    p = (platform or "").lower().strip()
    return "twitter" if p == "x" else p


# Path to the connection authorize endpoint per platform.
_AUTHORIZE_PATHS: dict[str, str] = {
    "youtube": "/api/v1/connections/youtube/authorize",
    "twitter": "/api/v1/connections/twitter/authorize",
    "facebook": "/api/v1/connections/facebook/authorize",
    "instagram": "/api/v1/connections/instagram/authorize",
    "linkedin": "/api/v1/connections/linkedin/authorize",
}


@router.get("/")
async def list_platforms():
    # TODO: implement connected publishing platforms
    return {"platforms": []}


@router.get("/status")
async def status_summary(
    db: AsyncSession = Depends(get_db),
    user: User = Depends(get_current_user),
) -> dict[str, Any]:
    """
    Return real connection status for supported platforms by reading
    `social_accounts` (encrypted token store used by publishers).
    """
    tiers: dict[str, AutomationTier] = {
        "youtube": "full_auto",
        "instagram": "full_auto",
        "facebook": "full_auto",
        "x": "full_auto",
        "linkedin": "full_auto",
    }

    rows = (
        await db.execute(select(SocialAccount).where(SocialAccount.user_id == user.id))
    ).scalars().all()
    by_platform: dict[str, SocialAccount] = {}
    for a in rows:
        by_platform[(a.platform or "").lower()] = a

    platforms: list[dict[str, Any]] = []
    for ui_key in ["youtube", "instagram", "facebook", "x", "linkedin"]:
        backend_key = _normalize(ui_key)
        a = by_platform.get(backend_key)
        access = try_decrypt_token(a.access_token_encrypted) if a else None
        refresh = try_decrypt_token(a.refresh_token_encrypted) if a else None
        connected = bool(a and a.is_active and (access or refresh))
        meta = a.metadata_json if (a and isinstance(a.metadata_json, dict)) else {}
        username = (
            str(meta.get("username") or "").strip()
            or str(meta.get("name") or "").strip()
            or (str(a.platform_user_id).strip() if (a and a.platform_user_id) else "")
        )
        platforms.append(
            {
                "platform": ui_key,
                "connected": connected,
                "account": {"username": username or "connected", "profile_image_url": meta.get("profile_image_url")}
                if connected
                else None,
                "token_expires_at": a.token_expires_at.isoformat() if (a and a.token_expires_at) else None,
                "last_used_at": a.updated_at.isoformat() if (a and a.updated_at) else None,
                "tier": tiers[ui_key],
            }
        )

    return {"platforms": platforms, "evaluation_mode": settings.EVALUATION_MODE}


class ConnectResponse(BaseModel):
    auth_url: str


@router.get("/connect/{platform}", response_model=ConnectResponse)
async def connect_platform(platform: PlatformKey) -> ConnectResponse:
    """
    Tell the frontend where the OAuth start endpoint lives for this platform.

    The actual authorize URL is generated by the connections router which is the
    only place that has access to per-provider OAuth client config (PKCE, scopes,
    state signing, etc.). The frontend calls that endpoint with auth headers and
    follows the returned `authorize_url`.
    """
    p = _normalize(platform)
    path = _AUTHORIZE_PATHS.get(p)
    if not path:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, detail="Platform not supported")
    return ConnectResponse(auth_url=path)


@router.delete("/{platform}")
async def disconnect_platform(
    platform: PlatformKey,
    db: AsyncSession = Depends(get_db),
    user: User = Depends(get_current_user),
) -> dict[str, Any]:
    """Remove the stored OAuth tokens for this platform (social_accounts)."""
    if settings.EVALUATION_MODE:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Evaluation mode is enabled: disconnecting platforms is disabled for demo safety.",
        )

    p = _normalize(platform)
    await db.execute(
        delete(SocialAccount).where(
            SocialAccount.user_id == user.id,
            SocialAccount.platform == p,
        )
    )
    await db.commit()
    return {"ok": True}


@router.post("/{platform}/refresh")
async def refresh_platform_token(
    platform: PlatformKey,
    db: AsyncSession = Depends(get_db),
    user: User = Depends(get_current_user),
) -> dict[str, Any]:
    """
    Best-effort refresh. The per-platform publisher modules already refresh tokens
    automatically on demand; this endpoint exists so the user can poke a refresh
    from the Connections UI. If the platform's refresh flow isn't supported (e.g.
    Meta long-lived tokens are exchanged at OAuth time only), we just return the
    stored expiry.
    """
    p = _normalize(platform)
    sa = (
        await db.execute(select(SocialAccount).where(SocialAccount.user_id == user.id, SocialAccount.platform == p))
    ).scalar_one_or_none()
    if sa is None:
        raise HTTPException(status.HTTP_404_NOT_FOUND, detail="Platform not connected")

    # Best-effort refresh per provider.
    if p == "twitter":
        # refreshes if needed, returns access token
        pub = TwitterPublisher()
        expires = sa.token_expires_at
        if expires is not None and expires.tzinfo is None:
            expires = expires.replace(tzinfo=timezone.utc)
        if expires and expires <= datetime.now(timezone.utc):
            _ = await pub.refresh_token(sa, db)
    elif p == "linkedin":
        pub = LinkedInPublisher()
        _ = await pub._ensure_access_token(sa, db)  # noqa: SLF001 (internal helper)
    elif p == "youtube":
        pub = YouTubePublisher()
        _ = await pub._build_credentials(sa, db)  # noqa: SLF001

    return {
        "ok": True,
        "platform": p,
        "expires_at": sa.token_expires_at.isoformat() if sa.token_expires_at else None,
    }


@router.get("/assisted/pending")
async def assisted_pending(
    db: AsyncSession = Depends(get_db),
    user: User = Depends(get_current_user),
):
    publisher = AssistedPublisher()
    items = await publisher.get_upcoming_assisted(str(user.id), db)
    return {"items": items}


async def _get_variant_for_user(variant_id: str, user_id: str, db: AsyncSession) -> PlatformVariant:
    stmt = (
        select(PlatformVariant)
        .join(ContentItem, ContentItem.id == PlatformVariant.content_item_id)
        .where(PlatformVariant.id == variant_id, ContentItem.user_id == user_id)
    )
    pv = (await db.execute(stmt)).scalar_one_or_none()
    if pv is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Platform variant not found")
    return pv


@router.post("/variants/{variant_id}/validate-media")
async def validate_variant_media(
    variant_id: str,
    db: AsyncSession = Depends(get_db),
    user: User = Depends(get_current_user),
) -> dict[str, Any]:
    """
    Preflight-only media validation.

    Runs the same ffprobe-based checks as the publish worker, plus best-effort Cloudinary
    auto-fix attempt (aspect crop) without publishing.
    """
    pv = await _get_variant_for_user(variant_id, str(user.id), db)
    if not pv.media_url:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Variant has no media_url to validate.")

    platform = str(pv.platform or "")
    original_url = str(pv.media_url)

    async def _run(url: str) -> dict[str, Any]:
        info = await probe_url(url)
        validate_for_platform(platform, info)
        return {
            "ok": True,
            "platform": platform,
            "media_url": url,
            "info": {
                "kind": info.kind,
                "bytes": info.bytes,
                "width": info.width,
                "height": info.height,
                "duration_seconds": info.duration_seconds,
                "format_name": info.format_name,
                "codec_name": info.codec_name,
            },
        }

    try:
        res = await _run(original_url)
        return {**res, "autofix_applied": False}
    except MediaValidationError as e:
        # Attempt Cloudinary auto-fix
        ms = MediaService()
        fixed = ms.resize_for_platform(original_url, platform, "video")
        if fixed.url != original_url:
            try:
                res2 = await _run(fixed.url)
                pv.media_url = fixed.url
                pv.metadata_json = {**(pv.metadata_json or {}), "media_autofix": True}
                pv.error_message = None
                db.add(pv)
                await db.commit()
                return {**res2, "autofix_applied": True, "original_media_url": original_url}
            except MediaValidationError:
                pass

        pv.error_message = f"Media validation failed: {e}"
        db.add(pv)
        await db.commit()
        return {
            "ok": False,
            "platform": platform,
            "media_url": original_url,
            "error": str(e),
            "autofix_applied": False,
        }


class ConfirmAssistedRequest(BaseModel):
    confirmed_at: datetime | None = None


@router.post("/assisted/{variant_id}/prepare")
async def assisted_prepare(
    variant_id: str,
    db: AsyncSession = Depends(get_db),
    user: User = Depends(get_current_user),
):
    pv = await _get_variant_for_user(variant_id, str(user.id), db)
    publisher = AssistedPublisher()

    platform = (pv.platform or "").lower()
    if platform == "instagram":
        pkg = await publisher.prepare_instagram_assisted(variant_id, db)
        return pkg.model_dump()
    if platform == "linkedin":
        pkg = await publisher.prepare_linkedin_assisted(variant_id, db)
        return pkg.model_dump()

    raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Variant is not an assisted platform")


@router.post("/assisted/{variant_id}/confirm")
async def assisted_confirm_published(
    variant_id: str,
    payload: ConfirmAssistedRequest,
    db: AsyncSession = Depends(get_db),
    user: User = Depends(get_current_user),
):
    _ = await _get_variant_for_user(variant_id, str(user.id), db)
    publisher = AssistedPublisher()
    confirmed_at = payload.confirmed_at or datetime.now(timezone.utc)
    result = await publisher.mark_as_published(variant_id, db, confirmed_at=confirmed_at)
    return result


@router.post("/youtube/publish/{content_id}")
async def publish_youtube(
    content_id: str,
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Trigger an immediate YouTube publish job for this content item."""
    pv = (
        await db.execute(
            select(PlatformVariant)
            .join(ContentItem, ContentItem.id == PlatformVariant.content_item_id)
            .where(ContentItem.user_id == user.id, ContentItem.id == content_id, PlatformVariant.platform == "youtube")
        )
    ).scalar_one_or_none()
    if pv is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="YouTube variant not found")
    ar = publish_content_task.delay(str(pv.id))
    return {"ok": True, "task_id": getattr(ar, "id", None), "platform_variant_id": str(pv.id)}


@router.post("/twitter/publish/{content_id}")
async def publish_twitter(
    content_id: str,
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Trigger a Twitter/X publish job for this content item."""
    pv = (
        await db.execute(
            select(PlatformVariant)
            .join(ContentItem, ContentItem.id == PlatformVariant.content_item_id)
            .where(ContentItem.user_id == user.id, ContentItem.id == content_id, PlatformVariant.platform.in_(["twitter", "x"]))
        )
    ).scalar_one_or_none()
    if pv is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Twitter variant not found")
    ar = publish_content_task.delay(str(pv.id))
    return {"ok": True, "task_id": getattr(ar, "id", None), "platform_variant_id": str(pv.id)}


@router.post("/facebook/publish/{content_id}")
async def publish_facebook(
    content_id: str,
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Trigger a Facebook publish job for this content item."""
    pv = (
        await db.execute(
            select(PlatformVariant)
            .join(ContentItem, ContentItem.id == PlatformVariant.content_item_id)
            .where(ContentItem.user_id == user.id, ContentItem.id == content_id, PlatformVariant.platform == "facebook")
        )
    ).scalar_one_or_none()
    if pv is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Facebook variant not found")
    ar = publish_content_task.delay(str(pv.id))
    return {"ok": True, "task_id": getattr(ar, "id", None), "platform_variant_id": str(pv.id)}


@router.post("/instagram/publish/{content_id}")
async def publish_instagram(
    content_id: str,
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Trigger an Instagram publish job for this content item."""
    pv = (
        await db.execute(
            select(PlatformVariant)
            .join(ContentItem, ContentItem.id == PlatformVariant.content_item_id)
            .where(ContentItem.user_id == user.id, ContentItem.id == content_id, PlatformVariant.platform == "instagram")
        )
    ).scalar_one_or_none()
    if pv is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Instagram variant not found")
    ar = publish_content_task.delay(str(pv.id))
    return {"ok": True, "task_id": getattr(ar, "id", None), "platform_variant_id": str(pv.id)}


@router.post("/linkedin/publish/{content_id}")
async def publish_linkedin(
    content_id: str,
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Trigger a LinkedIn publish job for this content item."""
    pv = (
        await db.execute(
            select(PlatformVariant)
            .join(ContentItem, ContentItem.id == PlatformVariant.content_item_id)
            .where(ContentItem.user_id == user.id, ContentItem.id == content_id, PlatformVariant.platform == "linkedin")
        )
    ).scalar_one_or_none()
    if pv is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="LinkedIn variant not found")
    ar = publish_content_task.delay(str(pv.id))
    return {"ok": True, "task_id": getattr(ar, "id", None), "platform_variant_id": str(pv.id)}


class PublishAllRequest(BaseModel):
    """When captions are generic AI fallbacks, the UI must set acknowledge_placeholder_captions=true."""

    acknowledge_placeholder_captions: bool = False


@router.post("/publish-all/{content_id}")
async def publish_all(
    content_id: str,
    payload: Annotated[PublishAllRequest | None, Body()] = None,
    user: User = Depends(get_current_user),
):
    """
    Body is optional for older clients; default is no acknowledgement (generic captions stay blocked server-side).
    """
    ack = bool(payload and payload.acknowledge_placeholder_captions)
    return await publish_to_all_platforms(
        str(user.id), content_id, acknowledge_placeholder_captions=ack
    )


class PublishSelectedRequest(BaseModel):
    platforms: list[str] = Field(default_factory=list)
    acknowledge_placeholder_captions: bool = False


@router.post("/publish-selected/{content_id}")
async def publish_selected(
    content_id: str,
    payload: PublishSelectedRequest,
    user: User = Depends(get_current_user),
):
    return await publish_to_all_platforms(
        str(user.id),
        content_id,
        platforms=payload.platforms,
        acknowledge_placeholder_captions=bool(payload.acknowledge_placeholder_captions),
    )

